language: node_js
node_js: 10
branches:
  only:
    - master
script: npm run build:prod
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  target_branch: root
  keep_history: false
  on:
    branch: master
  local-dir: dist
